# Fix all dialogs in Jetbrains products
windowrule = tag +jb, match:class ^jetbrains-.+$, match:float true
windowrule = stay_focused on, match:tag jb
windowrule = no_initial_focus on, match:tag jb
windowrule = focus_on_activate on, match:class ^jetbrains-(?!toolbox)

# center the pops excepting context menu
windowrule = move (monitor_w*0.3) (monitor_h*0.3), match:class ^jetbrains-(?!toolbox), match:title ^(?!win.*), match:float true
windowrule = size (monitor_w*0.4) (monitor_h*0.4), match:class ^jetbrains-(?!toolbox), match:title ^(?!win.*), match:float true

# fix tab dragging (always have a single space character as their title)
windowrule = no_initial_focus on, match:class ^(.*jetbrains.*)$, match:title ^\\s$
windowrule = no_focus on, match:class ^(.*jetbrains.*)$, match:title ^\\s$

windowrule {
  name = jetbrains_float_has_min_size
  min_size = 800 600
  match:class = ^(jetbrains-.*)$
  match:title = ^$
  match:float = 1
}
